domain_path: C:\IMR_Projects\IMR\Softcore_SA\Bootloader_Softcore_SA\MB_SSA_BL_Platform\export\MB_SSA_BL_Platform\sw\standalone_microblaze_0
app_src_dir: C:\Xilinx_Embedded_2024.2\Vitis\2024.2\data\embeddedsw\lib\sw_apps\srec_spi_bootloader
template: srec_spi_bootloader
lang: c
